/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside.vue')['default']
    Emoij: typeof import('./src/components/emoij.vue')['default']
    Emoji: typeof import('./src/components/emoji.vue')['default']
    List: typeof import('./src/components/contact/list.vue')['default']
    MeMsg: typeof import('./src/components/session/meMsg.vue')['default']
    OtherMsg: typeof import('./src/components/session/otherMsg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/contact/userInfo.vue')['default']
  }
}
