/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Emoji: typeof import('./src/components/emoji.vue')['default']
    Find: typeof import('./src/components/contact/find.vue')['default']
    List: typeof import('./src/components/contact/list.vue')['default']
    MeMsg: typeof import('./src/components/session/meMsg.vue')['default']
    Noticelist: typeof import('./src/components/contact/noticelist.vue')['default']
    OtherMsg: typeof import('./src/components/session/otherMsg.vue')['default']
    Previewmd: typeof import('./src/components/session/previewmd.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./src/components/contact/userInfo.vue')['default']
  }
}
